[package]
name = "ds_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
blstrs = "0.7.1"
ff = "0.13.0"
group = { version = "0.13.0", features = ["rand"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }

[dev-dependencies]
divan = "0.1.17"
